# docker-compose.yml
version: '3'
services:
  nats:
    image: nats:latest
    container_name: fuizu-nats
    restart: unless-stopped
    volumes:
      - ./nats_data:/nats_data
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
  fuizu-server:
    image: harbor.keia.one/fuizu/server:latest
    container_name: fuizu-server
    restart: unless-stopped
    environment:
      # Endpoint for NATS url
      - NATS_URL=nats:4222
      # If you have an API proxy unset this.
      # - GATEWAY_HTTP_PROXY_URL=
      - GATEWAY_QUEUE_TOKEN=discord token here
      # NATS subject to listen for identify requests on
      - GATEWAY_QUEUE_SUBJECT_REQUESTS=fuizu.requests
      # Interval in which to update session start limit (seconds)
      - GATEWAY_QUEUE_UPDATE_INTERVAL=43200